"""add created_at to feedback pages

Revision ID: d283b9547933
Revises: daca96f8ab17
Create Date: 2026-08-31 23:06:34.469731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd283b9547933'
down_revision: Union[str, Sequence[str], None] = 'daca96f8ab17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_pages', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_feedback_pages_id'), table_name='feedback_pages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feedback_pages_id'), 'feedback_pages', ['id'], unique=False)
    op.drop_column('feedback_pages', 'created_at')
    # ### end Alembic commands ###
