import { useEffect, useState } from 'react'
import { createFeedbackPage, getFeedback, getFeedbackPages, getPublicFeedbackPage, login, setFeedbackStatus, signup, submitFeedback } from './services/api'
import './App.css'

const STORAGE_KEY = 'anonfeed-session'
const readSession = () => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || null } catch { return null } }
const formatDate = (value) => new Date(value).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

function App() {
  const [route, setRoute] = useState(window.location.pathname)
  const [session, setSession] = useState(readSession)
  useEffect(() => { const update = () => setRoute(window.location.pathname); window.addEventListener('popstate', update); return () => window.removeEventListener('popstate', update) }, [])
  const navigate = (path) => { window.history.pushState({}, '', path); setRoute(path) }
  const saveSession = (data) => { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); setSession(data) }
  const loggedIn = (data) => { saveSession({ token: data.access_token, username: data.username }); navigate('/dashboard') }
  const logout = () => { localStorage.removeItem(STORAGE_KEY); setSession(null); navigate('/login') }
  const publicMatch = route.match(/^\/feedback\/([^/]+)\/(\d+)$/)
  const detailMatch = route.match(/^\/dashboard\/pages\/(\d+)$/)
  if (publicMatch) return <PublicPage username={decodeURIComponent(publicMatch[1])} pageId={Number(publicMatch[2])} />
  if (route === '/signup') return <AuthPage mode="signup" onSuccess={loggedIn} navigate={navigate} />
  if (route === '/login') return <AuthPage mode="login" onSuccess={loggedIn} navigate={navigate} />
  if (route === '/dashboard' || route === '/dashboard/new' || detailMatch) return session?.token ? <Dashboard session={session} logout={logout} navigate={navigate} detailId={detailMatch && Number(detailMatch[1])} /> : <AuthPage mode="login" onSuccess={loggedIn} navigate={navigate} />
  return <Landing navigate={navigate} />
}

function Brand({ compact = false }) { return <a className={`brand ${compact ? 'brand--compact' : ''}`} href="/" onClick={(e) => { e.preventDefault(); window.history.pushState({}, '', '/'); window.dispatchEvent(new PopStateEvent('popstate')) }}><span>✦</span> AnonFeed</a> }
function Landing({ navigate }) { return <main className="landing"><nav><Brand /></nav><section className="hero"><p className="eyebrow">Honest thoughts, shared freely</p><h1>Feedback feels better<br /><em>when it’s anonymous.</em></h1><p className="lede">Create a simple page, share one link, and hear what people really think — no sender names, no pressure.</p><div className="actions"><button className="button" onClick={() => navigate('/signup')}>Sign up <span>→</span></button><button className="text-button" onClick={() => navigate('/login')}>Already have an account? Log in</button></div></section><footer>Made for candid conversations.</footer></main> }

function AuthPage({ mode, onSuccess, navigate }) {
  const isSignup = mode === 'signup'; const [form, setForm] = useState({ username: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { if (isSignup) await signup(form); onSuccess(await login({ email: form.email, password: form.password })) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <main className="auth-shell"><nav><Brand /></nav><section className="auth-card"><p className="eyebrow">{isSignup ? 'Start collecting feedback' : 'Welcome back'}</p><h1>{isSignup ? 'Create your space.' : 'Log in to AnonFeed.'}</h1><p className="muted">{isSignup ? 'Your feedback pages will be ready in a minute.' : 'Pick up where your conversations left off.'}</p><form onSubmit={submit}>{isSignup && <Field label="Username" value={form.username} onChange={(v) => setForm({ ...form, username: v })} placeholder="e.g. alex" required />}<Field label="Email address" type="email" value={form.email} onChange={(v) => setForm({ ...form, email: v })} placeholder="you@example.com" required /><Field label="Password" type="password" value={form.password} onChange={(v) => setForm({ ...form, password: v })} placeholder="At least 8 characters" required />{error && <p className="notice notice--error">{error}</p>}<button className="button button--wide" disabled={busy}>{busy ? 'Please wait…' : isSignup ? 'Create account' : 'Log in'} <span>→</span></button><button type="button" className="text-button auth-switch" onClick={() => navigate(isSignup ? '/login' : '/signup')}>{isSignup ? 'Already have an account? Log in' : 'New here? Create an account'}</button></form></section></main>
}
function Field({ label, value, onChange, ...props }) { return <label className="field"><span>{label}</span><input value={value} onChange={(e) => onChange(e.target.value)} {...props} /></label> }

function Dashboard({ session, logout, navigate, detailId }) {
  const [pages, setPages] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = () => { setLoading(true); getFeedbackPages(session.token).then(setPages).catch((e) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(load, [session.token])
  if (detailId) { const page = pages.find((p) => p.id === detailId); return <DashboardFrame session={session} logout={logout}>{loading ? <p className="loading">Loading page…</p> : page ? <FeedbackDetail page={page} token={session.token} navigate={navigate} refresh={load} /> : <p className="notice notice--error">This feedback page could not be found.</p>}</DashboardFrame> }
  const openCreatedPage = (page) => {
    setPages((current) => [page, ...current])
    navigate(`/dashboard/pages/${page.id}`)
  }
  const isCreating = window.location.pathname === '/dashboard/new'
  return <DashboardFrame session={session} logout={logout}>{!isCreating && <section className="pages-header"><div><p className="eyebrow">Your workspace</p><h1>Feedback pages</h1><p className="muted">Create a shareable page or open one to read its anonymous feedback.</p></div></section>}{isCreating ? <CreatePage token={session.token} onCreated={openCreatedPage} /> : loading ? <p className="loading">Loading your pages…</p> : <><section className="page-grid"><button className="page-card page-card--new" onClick={() => navigate('/dashboard/new')}><span>+</span><strong>Create a new URL</strong><small>Start a separate feedback thread</small></button>{pages.map((page) => <button className="page-card" key={page.id} onClick={() => navigate(`/dashboard/pages/${page.id}`)}><span className="page-card__icon">✦</span><strong>{page.title}</strong><small>{page.accepting_feedback ? 'Accepting feedback' : 'Feedback paused'}</small><small className="page-card__date">Created {formatDate(page.created_at)}</small><span className="page-card__arrow">→</span></button>)}</section>{!pages.length && <p className="empty-copy">You haven’t created any feedback pages yet.</p>}</>}</DashboardFrame>
}
function DashboardFrame({ session, logout, children }) { return <main className="dashboard"><nav><Brand /><div className="nav-actions"><span className="account">@{session.username}</span><button className="button button--logout" onClick={logout}>Log out</button></div></nav>{children}</main> }
function CreatePage({ token, onCreated }) { const [form, setForm] = useState({ title: '', description: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { onCreated(await createFeedbackPage(form, token)) } catch (err) { setError(err.message) } finally { setBusy(false) } }; return <section className="setup-card"><h1>What would you like feedback on?</h1><form onSubmit={submit}><Field label="Page title" value={form.title} onChange={(v) => setForm({ ...form, title: v })} placeholder="Feedback for my portfolio" required /><label className="field"><span>Description <i>optional</i></span><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Give people a little context…" rows="3" /></label>{error && <p className="notice notice--error">{error}</p>}<button className="button button--wide" disabled={busy}>{busy ? 'Creating…' : 'Create feedback page'} <span>→</span></button></form></section> }
function FeedbackDetail({ page, token, navigate, refresh }) { const [feedback, setFeedback] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); useEffect(() => { getFeedback(page.id, token).then(setFeedback).catch((e) => setError(e.message)) }, [page.id, token]); const toggle = async () => { setBusy(true); try { await setFeedbackStatus(page.id, !page.accepting_feedback, token); refresh() } catch (e) { setError(e.message) } finally { setBusy(false) } }; const url = `${window.location.origin}${page.url}`; return <section className="detail-layout"><header className="detail-header"><button className="text-button back-link" onClick={() => navigate('/dashboard')}>← All feedback pages</button><p className="eyebrow">Feedback page</p><div className="page-context"><span>Title</span><h1>{page.title}</h1><span>Description</span><p className="muted">{page.description || 'No description added.'}</p></div></header><div className="detail-controls"><div className="link-box"><div><small>Share this link</small><strong>{url}</strong></div><button className="button button--small" onClick={() => navigator.clipboard?.writeText(url)}>Copy</button></div><div className="status-row"><div><strong>{page.accepting_feedback ? 'Feedback is open' : 'Feedback is paused'}</strong><span>{page.accepting_feedback ? 'Anyone with your link can send a note.' : 'Your public form is currently closed.'}</span></div><button className={`switch ${page.accepting_feedback ? 'switch--on' : ''}`} onClick={toggle} disabled={busy}><span /></button></div></div>{error && <p className="notice notice--error">{error}</p>}<aside className="inbox"><p className="eyebrow">Inbox</p><h2>Anonymous notes <span>{feedback.length}</span></h2>{feedback.length ? <div className="feedback-list">{feedback.map((note) => <article className="feedback-card" key={note.id}><span className="anon-mark">✦</span><p>{note.message}</p><small>Anonymous</small></article>)}</div> : <div className="empty"><span>◌</span><p>No feedback yet</p><small>Share your link to start receiving notes.</small></div>}</aside></section> }
function PublicPage({ username, pageId }) { const [page, setPage] = useState(null); const [message, setMessage] = useState(''); const [state, setState] = useState({ loading: true, error: '', sent: false, busy: false }); useEffect(() => { getPublicFeedbackPage(username, pageId).then(setPage).catch((e) => setState((s) => ({ ...s, error: e.message }))).finally(() => setState((s) => ({ ...s, loading: false }))) }, [username, pageId]); const send = async (e) => { e.preventDefault(); setState((s) => ({ ...s, busy: true, error: '' })); try { await submitFeedback(username, pageId, { message }); setMessage(''); setState({ loading: false, error: '', sent: true, busy: false }) } catch (err) { setState((s) => ({ ...s, error: err.message, busy: false })) } }; if (state.loading) return <main className="public-shell"><p className="loading">Loading this feedback page…</p></main>; if (!page) return <main className="public-shell"><section className="public-card"><h1>This page isn’t available.</h1><p>{state.error}</p></section></main>; const closed = !page.accepting_feedback; return <main className="public-shell"><section className="public-card"><div className="avatar">{page.title[0].toUpperCase()}</div><p className="eyebrow">Anonymous feedback for</p><div className="page-context"><span>Title</span><h1>{page.title}</h1>{page.description && <><span>Description</span><p className="muted">{page.description}</p></>}</div>{state.sent ? <div className="success"><span>✓</span><h2>Your note was sent.</h2><p>It was shared anonymously. Thanks for taking the time.</p><button className="text-button" onClick={() => setState((s) => ({ ...s, sent: false }))}>Send another note</button></div> : <form onSubmit={send} className="feedback-form"><label className="field"><span>Your message</span><textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Share your feedback here…" rows="4" required disabled={closed || state.busy} /></label>{closed && <p className="notice">This page is not accepting feedback right now.</p>}{state.error && <p className="notice notice--error">{state.error}</p>}<button className="button button--wide" disabled={closed || state.busy}>{state.busy ? 'Sending…' : 'Send anonymously'} <span>→</span></button></form>}</section></main> }
export default App
